blank_issues_enabled: true
contact_links:
  - name: Questions and aura sharing (Discord)
    url: https://discord.gg/HdRNYvKbY
    about: Help with setting up auras, install questions and shared auras.
