#!/usr/bin/env python3
"""
sv_bridge - workaround for the WoW: Forever beta client bug where SavedVariables
are WRITTEN on exit but never READ back on login (confirmed on build 1.60.1.69893+,
independently by Thunderz96/forever-addon-kit).

The client still executes normal addon Lua. So we copy each SavedVariables file
into an addon that loads first (!ForeverSVBridge), which re-creates the globals
before the real addons run.

Usage:
  python sv_bridge.py            # generate the seed once
  python sv_bridge.py --watch    # regenerate whenever a SavedVariables file changes
  python sv_bridge.py --list     # show what would be bridged

Run it AFTER exiting the game (that is when WoW writes the files), BEFORE launching again.
"""
import argparse
import os
import re
import sys
import time

CLIENT = r"D:\World of Warcraft\World of Warcraft\_classic_beta_"
SV_DIR = os.path.join(CLIENT, r"WTF\Account\YOUR_ACCOUNT\SavedVariables")
BRIDGE = os.path.join(CLIENT, r"Interface\AddOns\!ForeverSVBridge")

# Which SavedVariables to carry across sessions. Blizzard's own files are left alone.
BRIDGE_FILES = [
    "EverAuras.lua",          # the auras themselves
    "EverAurasOptions.lua",   # options window state
    "EverAurasArchive.lua",   # aura archive / rollback snapshots
    "ForeverDevInfo.lua",     # our diagnostics
    "BugSack.lua",
    "!BugGrabber.lua",
]

TOC = """## Interface: 16001
## Title: |cff33ff99!|r Forever SavedVariables Bridge
## Notes: Re-creates SavedVariables globals that the Forever beta client writes but never reads back. Generated by tools/sv_bridge.py - do not edit by hand.
## Author: Hackblarvest
## Version: {version}

seed.lua
"""

HEADER = """-- GENERATED by tools/sv_bridge.py - do not edit.
-- Workaround for the WoW: Forever beta client not reading SavedVariables back.
-- Each block only assigns if the global is still nil, so the day Blizzard fixes
-- the client this file quietly becomes a no-op.
-- Source: {src}
-- Generated: {when}

-- Tracks whether the crutch was actually needed this login. When Blizzard fixes
-- the client, seeded drops to 0 and the bridge can be deleted.
ForeverSVBridge = {{ generated = "{when}", seeded = 0, skipped = 0, names = {{}} }}
local function note(name, didSeed)
  if didSeed then
    ForeverSVBridge.seeded = ForeverSVBridge.seeded + 1
    ForeverSVBridge.names[#ForeverSVBridge.names + 1] = name
  else
    ForeverSVBridge.skipped = ForeverSVBridge.skipped + 1
  end
end

"""


def globals_in(text):
    """Top-level global names assigned in a SavedVariables file."""
    return re.findall(r'^(\w+)\s*=', text, re.M)


def build_seed(verbose=True):
    if not os.path.isdir(SV_DIR):
        sys.exit(f"SavedVariables folder not found: {SV_DIR}")
    parts, summary = [], []
    for name in BRIDGE_FILES:
        path = os.path.join(SV_DIR, name)
        if not os.path.exists(path):
            continue
        text = open(path, encoding="utf-8", errors="replace").read().strip()
        if not text:
            continue
        names = globals_in(text)
        # Skip files that only say "Foo = nil" - nothing to carry.
        meaningful = [n for n in names if not re.search(rf'^{re.escape(n)}\s*=\s*nil\s*$', text, re.M)]
        if not meaningful:
            summary.append((name, names, 0, "only nil"))
            continue
        guard = meaningful[0]
        parts.append(
            f"-- ==== {name} ({', '.join(names)}) ====\n"
            f"if {guard} == nil then\n{text}\nnote(\"{guard}\", true)\nelse\nnote(\"{guard}\", false)\nend\n"
        )
        # how many auras, if this is the aura DB
        auras = ""
        if name == "EverAuras.lua":
            m = re.search(r'\["displays"\] = \{(.*?)\n\t?\},', text, re.S)
            n = len(re.findall(r'^\t\t\["([^"]+)"\]', m.group(1), re.M)) if m else 0
            auras = f"{n} auras"
        summary.append((name, meaningful, len(text), auras))

    os.makedirs(BRIDGE, exist_ok=True)
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    seed = HEADER.format(src=SV_DIR, when=stamp) + "\n".join(parts)
    with open(os.path.join(BRIDGE, "seed.lua"), "w", encoding="utf-8", newline="\n") as f:
        f.write(seed)
    with open(os.path.join(BRIDGE, "!ForeverSVBridge.toc"), "w", encoding="utf-8", newline="\n") as f:
        f.write(TOC.format(version=stamp))

    if verbose:
        print(f"seed.lua written: {len(seed)} bytes -> {BRIDGE}")
        for name, names, size, note in summary:
            print(f"  {name:22s} {', '.join(names):34s} {size:>7} B  {note}")
    return seed


def watch():
    print(f"watching {SV_DIR} (Ctrl+C to stop)")
    last = {}
    while True:
        changed = False
        for name in BRIDGE_FILES:
            p = os.path.join(SV_DIR, name)
            try:
                m = os.path.getmtime(p)
            except OSError:
                continue
            if last.get(name) != m:
                last[name] = m
                changed = True
        if changed:
            print(f"[{time.strftime('%H:%M:%S')}] change detected, regenerating")
            try:
                build_seed(verbose=False)
                print("  seed updated")
            except Exception as e:
                print("  failed:", e)
        # Fast poll: on /reload WoW writes SavedVariables and reloads almost immediately,
        # so the seed has to be rebuilt before the addons come back up.
        time.sleep(0.4)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--watch", action="store_true", help="regenerate whenever SavedVariables change")
    ap.add_argument("--list", action="store_true", help="just show what would be bridged")
    a = ap.parse_args()
    if a.watch:
        build_seed()
        watch()
    else:
        build_seed()
